const fields={emplacement:$('#f_emplacement'),nom:$('#f_nom'),rue:$('#f_rue'),dimension:$('#f_dimension'),statut:$('#f_statut'),x_pct:$('#f_x'),y_pct:$('#f_y')};
let dirty=false;window.isSaving=false;window.adminToken=null;
function markDirty(){dirty=true;$('#dirty').textContent='Modifications non sauvegardées sur Google.';statusEl.textContent='Modifications locales — cliquez sur Sauvegarder sur Google.'}
window.hasDraft=()=>dirty;
function resetEditor(){dirty=false;$('#dirty').textContent='Aucune modification en attente.';$('#editor').classList.add('hidden');$('#empty').classList.remove('hidden')}
function fillCoordinates(r){fields.x_pct.value=r.x_pct.toFixed(4);fields.y_pct.value=r.y_pct.toFixed(4)}
function fillForm(r){if(!window.isUnlocked)return;$('#empty').classList.add('hidden');$('#editor').classList.remove('hidden');Object.entries(fields).forEach(([k,el])=>el.value=['x_pct','y_pct'].includes(k)?Number(r[k]).toFixed(4):r[k]||'')}
function applyForm(){if(selected===null)return true;if(!$('#editor').reportValidity())return false;const next={};Object.entries(fields).forEach(([k,el])=>next[k]=['x_pct','y_pct'].includes(k)?Number(el.value):el.value.trim());if(rows.some((r,i)=>i!==selected&&r.emplacement.toUpperCase()===next.emplacement.toUpperCase())){statusEl.textContent='Ce numéro existe déjà.';return false}if(Object.keys(next).some(k=>next[k]!==rows[selected][k])){rows[selected]=next;markDirty();render()}return true}
window.commitSelected=applyForm;
function controls(){for(const id of ['#saveFile','#add','#importFile'])$(id).disabled=!window.isUnlocked||window.isSaving;$('#logout').classList.toggle('hidden',!window.isUnlocked);$('#login').classList.toggle('hidden',window.isUnlocked);$('#reload').disabled=window.isSaving;$('#editor').querySelectorAll('input,button').forEach(el=>el.disabled=window.isSaving)}
$('#editor').onsubmit=e=>{e.preventDefault();if(window.isUnlocked&&!window.isSaving)applyForm()};
$('#editor').oninput=()=>{if(window.isUnlocked)markDirty()};
$('#login').onsubmit=async e=>{e.preventDefault();const button=$('#login button');button.disabled=true;try{const auth=await CloudApi.login($('#password').value);window.adminToken=auth.token;const data=await CloudApi.read(auth.token);rows=data.rows.map(cleanRow);cloudVersion=data.version;selected=null;window.isUnlocked=true;$('#password').value='';resetEditor();render();controls();$('#empty').textContent='Cliquez sur un marqueur, puis déplacez-le ou modifiez ses champs.';statusEl.textContent='Connecté — données Google chargées.'}catch(err){statusEl.textContent=err.message}finally{button.disabled=false}};
$('#add').onclick=()=>{if(!window.isUnlocked||window.isSaving||!applyForm())return;let n=1,id;do{id='N'+n++}while(rows.some(r=>r.emplacement===id));rows.push({emplacement:id,x_pct:50,y_pct:50,nom:'',rue:'Place de la Gare',dimension:'',statut:''});selected=rows.length-1;render();fillForm(rows[selected]);markDirty()};
$('#remove').onclick=()=>{if(!window.isUnlocked||window.isSaving||selected===null||!confirm(`Supprimer ${rows[selected].emplacement} ?`))return;rows.splice(selected,1);selected=null;render();resetEditor();markDirty()};
$('#saveFile').onclick=async()=>{if(!window.isUnlocked||!cloudVersion||!applyForm())return;window.isSaving=true;controls();statusEl.textContent='Sauvegarde sur Google…';try{const data=await CloudApi.save(window.adminToken,rows,cloudVersion);rows=data.rows.map(cleanRow);cloudVersion=data.version;selected=null;resetEditor();render();statusEl.textContent='Sauvegardé sur Google. Le public s’actualise sous 30 secondes.'}catch(err){statusEl.textContent='Sauvegarde non confirmée : '+err.message}finally{window.isSaving=false;controls()}};
$('#logout').onclick=async()=>{if(dirty&&!confirm('Quitter sans sauvegarder ?'))return;try{await CloudApi.logout(window.adminToken)}catch(e){}window.adminToken=null;window.isUnlocked=false;selected=null;resetEditor();controls();await loadData()};
$('#exportFile').onclick=()=>{if(window.isUnlocked&&!applyForm())return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)+'\n'],{type:'application/json'}));a.download='emplacements.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importFile').onchange=async e=>{if(!window.isUnlocked)return;try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data)||data.length>5000)throw Error('Format invalide.');const next=data.map(cleanRow);if(next.some(r=>!validRow(r))||new Set(next.map(r=>r.emplacement.toUpperCase())).size!==next.length)throw Error('Numéros ou positions invalides/dupliqués.');if(!confirm(`Remplacer la liste locale par ${next.length} emplacements ? Google ne sera modifié qu’après sauvegarde.`))return;rows=next;selected=null;render();resetEditor();markDirty()}catch(err){statusEl.textContent='Import refusé : '+err.message}finally{e.target.value=''}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});controls();
