const DEFAULT_ROWS=Array.isArray(window.EMPLACEMENTS_DATA)?window.EMPLACEMENTS_DATA:[{emplacement:"G66",x_pct:55.5,y_pct:52.5,nom:"",rue:"Place de la Gare",dimension:"",statut:"Exemple"}];
const $=s=>document.querySelector(s), view=$("#view"), stage=$("#stage"), map=$("#map"), markers=$("#markers"), statusEl=$("#status");
if(!('sectorEl' in window)){
  Object.defineProperty(window, 'sectorEl', {
    get() { return document.querySelector('#sector') || { value: '', addEventListener() {}, append() {} }; },
    configurable: true
  });
}
let rows=[],sc=1,tx=0,ty=0,min=.1,max=8,panning=false,startX=0,startY=0,originX=0,originY=0,selected=null,cloudVersion=null,loadEpoch=0;
function transform(){stage.style.transform=`translate(${tx}px,${ty}px) scale(${sc})`}
function fit(){if(!map.naturalWidth)return;sc=Math.min(view.clientWidth/map.naturalWidth,view.clientHeight/map.naturalHeight);min=sc*.65;tx=(view.clientWidth-map.naturalWidth*sc)/2;ty=(view.clientHeight-map.naturalHeight*sc)/2;transform()}
function zoom(mult,cx=view.clientWidth/2,cy=view.clientHeight/2){const old=sc,ns=Math.max(min,Math.min(max,sc*mult)),wx=(cx-tx)/old,wy=(cy-ty)/old;sc=ns;tx=cx-wx*sc;ty=cy-wy*sc;transform()}
function coordinate(v){return v===null||v===undefined||typeof v==='boolean'||String(v).trim()===''?NaN:Number(v)}
function cleanRow(r){return {emplacement:String(r.emplacement||r.id||"").trim(),x_pct:coordinate(r.x_pct??r.x),y_pct:coordinate(r.y_pct??r.y),nom:String(r.nom||r.exposant||""),rue:String(r.rue||""),dimension:String(r.dimension||""),statut:String(r.statut||"")}}
function isConstructionMode(){const local=localStorage.getItem('brocante_construction_mode');if(local!==null)return local==='true';const cfg=rows.find(r=>r.emplacement==='__SITE_MODE__');if(cfg)return cfg.statut==='construction';return window.BROCANTE_CONFIG?.constructionMode!==false}
function updatePublicModeUI(){if(window.ADMIN_MODE)return;const isConst=isConstructionMode(),ctrl=$('#headerControls'),notice=$('#constructionNotice'),note=$('#sectorNote');if(ctrl)ctrl.classList.toggle('hidden',isConst);if(notice)notice.classList.toggle('hidden',!isConst);if(markers)markers.classList.toggle('hidden',isConst);if(note&&isConst)note.textContent='10 secteurs · Consultation des emplacements bientôt disponible'}
async function loadData(){const epoch=++loadEpoch,token=window.adminToken;if(!CloudApi.configured){rows=DEFAULT_ROWS.map(cleanRow).filter(validRow);statusEl.textContent="Connexion Google pas encore activée — consultez le guide";render();updatePublicModeUI();return}try{const data=await CloudApi.read(token);if(epoch!==loadEpoch||token!==window.adminToken)return;rows=data.rows.map(cleanRow);cloudVersion=data.version;selected=null;const outlineCfg=rows.find(r=>r.emplacement==='__SECTOR_OUTLINES__');if(outlineCfg&&outlineCfg.nom&&window.applyCustomSectorOutlines){window.applyCustomSectorOutlines(outlineCfg.nom);localStorage.setItem('brocante_sector_outlines',outlineCfg.nom)}else if(localStorage.getItem('brocante_sector_outlines')&&window.applyCustomSectorOutlines){window.applyCustomSectorOutlines(localStorage.getItem('brocante_sector_outlines'))}render();updatePublicModeUI();if(window.resetEditor)resetEditor();if(window.updateAdminToggleUI)window.updateAdminToggleUI();const count=rows.filter(r=>!['__SITE_MODE__','__SECTOR_OUTLINES__'].includes(r.emplacement)).length;statusEl.textContent=`${count} emplacement(s) à jour depuis Google — ${new Date().toLocaleTimeString('fr-BE')}`}catch(e){if(epoch===loadEpoch)statusEl.textContent="Google indisponible : "+e.message}}
function validRow(r){return r.emplacement&&Number.isFinite(r.x_pct)&&Number.isFinite(r.y_pct)&&r.x_pct>=-998&&r.x_pct<=100&&r.y_pct>=-998&&r.y_pct<=100}
function render(){markers.innerHTML="";if(!window.ADMIN_MODE&&isConstructionMode()){markers.classList.add('hidden');return}markers.classList.remove('hidden');rows.forEach((r,i)=>{if(['__SITE_MODE__','__SECTOR_OUTLINES__'].includes(r.emplacement))return;const m=document.createElement("div");m.className="marker"+(window.ADMIN_MODE?" admin-marker":"")+(i===selected?" selected":"");m.dataset.index=i;m.style.left=r.x_pct/100*map.naturalWidth+"px";m.style.top=r.y_pct/100*map.naturalHeight+"px";m.textContent=r.emplacement;const tip=document.createElement("span");tip.textContent=r.nom?`${r.emplacement} — ${r.nom}`:r.emplacement;m.appendChild(tip);m.addEventListener("pointerdown",e=>markerDown(e,i));m.addEventListener("click",e=>{e.stopPropagation();selectRow(i,!window.ADMIN_MODE)});markers.appendChild(m)})}
function selectRow(i,center=false){
  if(window.ADMIN_MODE&&(window.isSaving||(selected!==null&&window.isUnlocked&&window.commitSelected&&!commitSelected())))return;
  selected=i;render();const r=rows[i];
  if(center){const px=r.x_pct/100*map.naturalWidth,py=r.y_pct/100*map.naturalHeight;sc=Math.max(sc,Math.min(max,3.2));tx=view.clientWidth/2-px*sc;ty=view.clientHeight/2-py*sc;transform()}
  if(window.ADMIN_MODE){fillForm(r);return}
  $("#info").style.display="block";$("#iid").textContent=r.emplacement;$("#irue").textContent=r.rue||"";$("#inom").textContent=r.nom?"Exposant : "+r.nom:"";$("#idim").textContent=r.dimension?"Dimension : "+r.dimension:"";$("#istat").textContent=r.statut?"Statut : "+r.statut:"";
}
function markerDown(e,i){e.stopPropagation();selectRow(i,false);if(!window.ADMIN_MODE||!window.isUnlocked||window.isSaving||selected!==i)return;e.preventDefault();const move=ev=>{const rect=view.getBoundingClientRect(),x=(ev.clientX-rect.left-tx)/sc,y=(ev.clientY-rect.top-ty)/sc;rows[i].x_pct=Math.max(0,Math.min(100,x/map.naturalWidth*100));rows[i].y_pct=Math.max(0,Math.min(100,y/map.naturalHeight*100));const m=markers.children[i];m.style.left=rows[i].x_pct/100*map.naturalWidth+"px";m.style.top=rows[i].y_pct/100*map.naturalHeight+"px";fillCoordinates(rows[i]);markDirty()};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);window.removeEventListener("pointercancel",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);window.addEventListener("pointercancel",up)}
function search(){const q=($("#search")?$("#search").value:"").trim().toLocaleUpperCase("fr");const i=rows.findIndex(r=>r.emplacement!=='__SITE_MODE__'&&r.emplacement.toLocaleUpperCase("fr")===q);if(i>=0){selectRow(i,true);statusEl.textContent=`${rows[i].emplacement} trouvé`}else statusEl.textContent=`${q||"Emplacement"} introuvable`}
if($("#go"))$("#go").onclick=search;if($("#search"))$("#search").onkeydown=e=>{if(e.key==="Enter")search()};$("#fit").onclick=fit;$("#plus").onclick=()=>zoom(1.25);$("#minus").onclick=()=>zoom(.8);
view.onwheel=e=>{e.preventDefault();const r=view.getBoundingClientRect();zoom(e.deltaY<0?1.12:.89,e.clientX-r.left,e.clientY-r.top)};
let activePointers=new Map(),initialPinchDist=null,initialPinchScale=1;
view.onpointerdown=e=>{if(e.target.closest(".marker")||e.target.closest(".panel")||e.target.closest(".sector-legend")||e.target.closest(".controls")||e.target.closest("circle")||e.target.closest(".vertex-handle"))return;activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activePointers.size===1){panning=true;view.classList.add("panning");startX=e.clientX;startY=e.clientY;originX=tx;originY=ty}else if(activePointers.size===2){panning=false;const pts=Array.from(activePointers.values());initialPinchDist=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);initialPinchScale=sc}try{view.setPointerCapture(e.pointerId)}catch(_){}};
view.onpointermove=e=>{if(!activePointers.has(e.pointerId))return;activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activePointers.size===2&&initialPinchDist){const pts=Array.from(activePointers.values()),dist=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(dist>0){const rect=view.getBoundingClientRect(),midX=(pts[0].x+pts[1].x)/2-rect.left,midY=(pts[0].y+pts[1].y)/2-rect.top,targetScale=Math.max(min,Math.min(max,initialPinchScale*(dist/initialPinchDist)));zoom(targetScale/sc,midX,midY)}}else if(panning&&activePointers.size===1){tx=originX+e.clientX-startX;ty=originY+e.clientY-startY;transform()}};
const handlePointerEnd=e=>{activePointers.delete(e.pointerId);if(activePointers.size<2)initialPinchDist=null;if(activePointers.size===0){panning=false;view.classList.remove("panning")}};
view.onpointerup=handlePointerEnd;view.onpointercancel=handlePointerEnd;
updatePublicModeUI();map.onload=()=>{render();fit()};if(map.complete&&map.naturalWidth)fit();window.onresize=fit;loadData();
$("#reload").onclick=()=>{if(window.hasDraft&&window.hasDraft()&&!confirm("Abandonner les modifications locales et recharger Google ?"))return;loadData()};
if(!window.ADMIN_MODE)setInterval(()=>{if(!document.hidden&&CloudApi.configured)loadData()},Math.max(10,window.BROCANTE_CONFIG.refreshSeconds||30)*1000);
