let mapMode='ensemble';
const sectorEl=$('#sector');
function globalToMap(p){return mapMode==='gare'?unproject(GARE_TRANSFORM,p):mapMode==='sud'?unproject(SOUTH_TRANSFORM,p):p}
function mapToGlobal(p){return mapMode==='gare'?project(GARE_TRANSFORM,p):mapMode==='sud'?project(SOUTH_TRANSFORM,p):p}
function pointOnMap(r){return globalToMap(globalPoint(r))}
function displayedCoordinates(r){const p=pointOnMap(r);return [p[0]/map.naturalWidth*100,p[1]/map.naturalHeight*100]}
function fromDisplayed(rue,x,y){return storedPoint(rue,mapToGlobal([x/100*map.naturalWidth,y/100*map.naturalHeight]))}
function drawZones(){const svg=$('#zones');svg.innerHTML='';svg.setAttribute('width',map.naturalWidth);svg.setAttribute('height',map.naturalHeight);svg.setAttribute('viewBox',`0 0 ${map.naturalWidth} ${map.naturalHeight}`);if(!map.naturalWidth)return;for(const s of SECTORS){if(mapMode==='gare')continue;const g=document.createElementNS('http://www.w3.org/2000/svg','g'),line=document.createElementNS(g.namespaceURI,'polyline');line.setAttribute('points',s.path.map(p=>globalToMap(p).join(',')).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke',s.color);line.setAttribute('stroke-width',mapMode==='sud'?s.width*1.6:s.width);line.setAttribute('stroke-opacity',!sectorEl.value||sectorEl.value===s.id?'.6':'.12');line.setAttribute('stroke-linejoin','round');g.append(line);const title=document.createElementNS(g.namespaceURI,'title');title.textContent=s.name;g.append(title);g.setAttribute('role','button');g.setAttribute('tabindex','0');g.setAttribute('aria-label',s.name);g.onclick=e=>{e.stopPropagation();chooseSector(s.id)};g.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();chooseSector(s.id)}};svg.append(g)}}
function commit(){return !window.ADMIN_MODE||(!window.isSaving&&(selected===null||!window.isUnlocked||!window.commitSelected||commitSelected()))}
function switchMap(mode){mapMode=mode;map.src=mode==='gare'?'zone-gare-reference.png':mode==='sud'?'plan-sud.png':'plan-centre.png';map.alt=mode==='gare'?'Vue détaillée de la Gare':mode==='sud'?'Grand-Rue et place Bantigny, partie sud':'Vue des dix secteurs de la brocante';}
function chooseSector(id){if(!commit()){sectorEl.value=sectorEl.dataset.previous||'';return}sectorEl.value=id;sectorEl.dataset.previous=id;selected=null;if(window.resetSelection)resetSelection();if($('#info'))$('#info').style.display='none';const sec=SECTORS.find(s=>s.id===id);switchMap(sec?.legacy?'gare':id==='bantigny'?'sud':'ensemble');$('#sectorNote').textContent=sec?sec.name+(sec.note?' · '+sec.note:''):'10 secteurs · Choisissez un secteur pour voir ses emplacements';render()}
render=function(){markers.innerHTML='';rows.forEach((r,i)=>{const sec=sectorFor(r.rue),p=pointOnMap(r),m=document.createElement('button');m.type='button';m.className='marker'+(window.ADMIN_MODE?' admin-marker':'')+(i===selected?' selected':'');m.dataset.index=i;m.hidden=!!sectorEl.value&&sec?.id!==sectorEl.value||p[0]<0||p[1]<0||p[0]>map.naturalWidth||p[1]>map.naturalHeight;m.style.left=p[0]+'px';m.style.top=p[1]+'px';m.style.backgroundColor=i===selected?'#ef4444':sec?.color||'#7c3aed';m.textContent=r.emplacement;m.setAttribute('aria-label',`${r.emplacement} — ${sec?.name||r.rue}`);const tip=document.createElement('span');tip.className='tip';tip.textContent=r.emplacement+' — '+(sec?.name||r.rue);m.append(tip);m.onpointerdown=e=>markerDown(e,i);m.onclick=e=>{e.stopPropagation();selectRow(i)};markers.append(m)});drawZones()};
selectRow=function(i,center=false){if(!commit())return;const r=rows[i],sec=sectorFor(r.rue);if(sectorEl.value&&sectorEl.value!==sec?.id){sectorEl.value=sec?.id||'';sectorEl.dataset.previous=sectorEl.value}const p=pointOnMap(r);if(p[0]<0||p[1]<0||p[0]>map.naturalWidth||p[1]>map.naturalHeight){switchMap(sec?.legacy?'gare':'sud');map.addEventListener('load',()=>selectRow(i,center),{once:true});return}selected=i;render();if(center){sc=Math.max(sc,Math.min(max,3.2));const w=Math.max(220,view.clientWidth-(window.ADMIN_MODE&&view.clientWidth>700?360:0));tx=w/2-p[0]*sc;ty=view.clientHeight/2-p[1]*sc;transform()}if(window.ADMIN_MODE){fillForm(r);return}$('#info').style.display='block';$('#iid').textContent=r.emplacement;$('#irue').textContent=sec?.name||r.rue;$('#inom').textContent=r.nom?'Exposant : '+r.nom:'';$('#idim').textContent=r.dimension?'Dimension : '+r.dimension:'';$('#istat').textContent=r.statut?'Statut : '+r.statut:'';};
markerDown=function(e,i){e.stopPropagation();selectRow(i);if(!window.ADMIN_MODE||!window.isUnlocked||window.isSaving||selected!==i)return;e.preventDefault();const move=ev=>{const rect=view.getBoundingClientRect(),q=storedPoint(rows[i].rue,mapToGlobal([(ev.clientX-rect.left-tx)/sc,(ev.clientY-rect.top-ty)/sc]));if(q.some(n=>!Number.isFinite(n)||n<0||n>100))return;rows[i].x_pct=q[0];rows[i].y_pct=q[1];const p=pointOnMap(rows[i]),m=markers.children[i];m.style.left=p[0]+'px';m.style.top=p[1]+'px';fillCoordinates(rows[i]);markDirty()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up)};
SECTORS.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;sectorEl.append(o)});sectorEl.onchange=()=>chooseSector(sectorEl.value);$('#baseMap').onchange=e=>{if(!commit()){e.target.value=mapMode;return}switchMap(e.target.value);if(window.ADMIN_MODE&&selected!==null)map.addEventListener('load',()=>fillCoordinates(rows[selected]),{once:true})};const oldMapLoad=map.onload;map.onload=()=>{$('#baseMap').value=mapMode;oldMapLoad();if(window.ADMIN_MODE&&selected!==null)fillCoordinates(rows[selected]);};
$('#fit').onclick=()=>{if(commit())chooseSector('')};view.onwheel=e=>{if(e.target.closest('.panel'))return;e.preventDefault();const r=view.getBoundingClientRect();zoom(e.deltaY<0?1.12:.89,e.clientX-r.left,e.clientY-r.top)};
switchMap('ensemble');
